# The cnfig for travis CI
sudo: required

language: python

python:
    - "2.7"

services:  
    - docker

before_install:  
    # reinstall docker-compose at specific version
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose

script:  
    - docker version
    - docker-compose version

