#Run docker container in the background
#docker-compose up -d
version: '2'
services:
  aws-elk-billing:
    build : .
    environment:
    - ENV=debug
    - DEBIAN_FRONTEND=noninteractive
    - TERM=xterm
    volumes:
    - .:/aws-elk-billing
    depends_on:
    - kibana
    - logstash
    - elasticsearch
    links:
    - kibana:kibana.priceboard.in
    - logstash:db.logstash.priceboard.in
    - elasticsearch:db.elasticsearch.priceboard.in
    extends:
     file: ../docker-compose.aws.prod-key.yml
     service: env_var
    command: bash -c "python /aws-elk-billing/orchestrate.py"

  logstash:
    image: droidlabour/logstash:2.3
    ports:
    - 5140:5140
    links:
    - elasticsearch:db.elasticsearch.priceboard.in
    depends_on:
    - elasticsearch
    volumes:
    - ./logstash.conf:/logstash.conf
    command: "logstash -f /logstash.conf"

  kibana:
    image: droidlabour/kibana:4.5
    ports:
    - 5601:5601
    links:
    - elasticsearch:db.elasticsearch.priceboard.in
    depends_on:
    - elasticsearch

  elasticsearch:
    image: droidlabour/elasticsearch:2.3.3
    ports:
    - 9200:9200
    - 9300:9300
